repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
<<<<<<< HEAD
    -   id: check-toml
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
    -   id: bandit
=======
    -   id: name-tests-test
    -   id: check-toml
>>>>>>> 725e02f (Poetry, pre-commit, and project structure setup)
