---
on:
  push:
    paths:
      - rasterioxyz/**
      - .github/**
      - tests/**
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set-up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry and dependencies
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
      - name: Run mypy
        run: poetry run mypy rasterioxyz tests
