name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'main'
    steps:
      - uses: actions/checkout@v4
      - name: Set-up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: pip install uv
      - name: Build package
        run: uv build
      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
